# Generated by Django 4.2.2 on 2023-07-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newa', '0003_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
