# Generated by Django 4.2.2 on 2023-08-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newa', '0005_remove_article_category_delete_createform_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='International',
            new_name='Content',
        ),
    ]
